name:                sed-transpile
version:             0.1.0.0
github:              "githubuser/sed-transpile"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sed-transpile#readme>

dependencies:
- base >= 4.7 && < 5
- free >=5.1.7
- mtl >=2.2.2
- containers >=0.6.4.1
- mmorph >=1.1.5
- transformers >=0.5.6.2
- megaparsec >=9.2.0
- parser-combinators >=1.3.0
- deriving-compat >=0.6

library:
  source-dirs: src

executables:
  sed-transpile-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sed-transpile

tests:
  sed-transpile-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sed-transpile
